kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.089199810895077461
    roll: -0
    pitch: 0
    yaw: 4.3059993117992169e-05
  upper_arm:
    x: 5.5365484728955423e-05
    y: 0
    z: 0
    roll: 1.5709857083324044
    pitch: 0
    yaw: 3.5577001237708363e-05
  forearm:
    x: -0.42513770449182597
    y: 0
    z: 0
    roll: 0.0008277762334375242
    pitch: -0.00013463947927839029
    yaw: 4.6146119437798927e-05
  wrist_1:
    x: -0.39216525686465109
    y: -0.00060610137554146669
    z: 0.10974184411450603
    roll: 0.0055229180615532286
    pitch: -0.00058333718242703546
    yaw: -9.4621675360251312e-05
  wrist_2:
    x: -2.1346156219629106e-05
    y: -0.094759069212117977
    z: 4.3982960967429519e-05
    roll: 1.5703321711401972
    pitch: 0
    yaw: -3.0248530057902165e-05
  wrist_3:
    x: 0.00013068132837301035
    y: 0.082327729579917838
    z: 4.2673097146746556e-05
    roll: 1.5713146587535556
    pitch: 3.1415926535897931
    yaw: -3.1415665984806553
  hash: calib_16854361342318436294